# Screen
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# Asteroids
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPEED = 50

# Player
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 250
PLAYER_SPEED = 200

# Bullets
BULLET_RADIUS = 5
BULLET_SPEED = 300
BULLET_LIFETIME = 2.5  # seconds
BULLET_DAMAGE = 10

# Collisions
